version: '3.9'

services:
  chatbot-app:
    build: .
    env_file:
      - .env
    environment:
      - HF_HOME = /workspace/hf_cache
    volumes:
      - "E:/hf_cache:/workspace/hf_cache"
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  qdrant_data: